# This Cloud Formation template is used for deployment infrastructure
AWSTemplateFormatVersion: 2010-09-09
Description: Code and Coffee Service Deployment Infrastructure
Parameters:
  RandomSeed:
    Type: String
    Description: A random seed to use for generating unique names.
  Environment:
    Type: String
    Description: The name of the environment.
Resources:
  WebResourcesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub code-and-coffee-service-deploy-${Environment}-${RandomSeed}
