name: Development Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          RANDOM_SEED: ${{ secrets.RANDOM_SEED }}
          VITE_ROOT_URL: https://d1c0gelty0u4g.cloudfront.net
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
          GOOGLE_API_HOST: ${{ secrets.GOOGLE_API_HOST }}
          MEETUP_API_HOST: ${{ secrets.MEETUP_API_HOST }}
          STAGE: development
          SETTINGS_HOST: ${{ secrets.SETTINGS_HOST }}
          API_KEY: ${{ secrets.API_KEY }}
          GH_API_BASE_URL: ${{ secrets.GH_API_BASE_URL }}
          GH_AUTH_KEY: ${{ secrets.GH_AUTH_KEY }}
          EMAIL_APP_URL: ${{ secrets.EMAIL_APP_URL }}
