name: Production Deploy

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          RANDOM_SEED: ${{ secrets.RANDOM_SEED }}
          VITE_ROOT_URL: https://d3i0k8ieonilzl.cloudfront.net
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
          GOOGLE_API_HOST: ${{ secrets.GOOGLE_API_HOST }}
          MEETUP_API_HOST: ${{ secrets.MEETUP_API_HOST }}
          STAGE: production
          SETTINGS_HOST: ${{ secrets.SETTINGS_HOST }}
          API_KEY: ${{ secrets.API_KEY }}
